language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run coverage
env:
  global:
    # FIREBASE_TOKEN
    - secure: 0d6HLGrlOD9t3sRFksInRxdnuSh/NK536wtHuzr8HmYbV5mSENiNJt6zT9pxVAHzmBVY5j+TS/A1NLtHxVJfyjW1tJpeLUXr+UN7sgDAenvO9E/BUx8PQ8E35Vbcw/xgHKcJW/KCve8rt0nTQhVtl9nNgeEJgo5o4cJ4TExi3IwTbeGV0vNmEimVO+dp6wjWhbDyZTO3SOwLGlcRzFUT5XjssKQ5P+tKqObKlD0nqTt/TI3BHSWA3bmu9CNNK6awJYLUYwDqcbVIBCw9Bp4TICZ95egU2uQRbC230CZ1Zm+QoSWBUzudpMzU7hz0MdquFogzrAjI7SjTAP8nkvFSi7tCLFExJatOZBTqEhNqB5XFq6sLgP/E8lqZkSoHAMVUcok7ZcIxkALDQ1PsW/NmqILYphd0hbP7jcuU4mqTLwEX4iz0EuVPgTrefJvAY9dRlur6FEenFtHlT3FTmj051TuxHNmwv69+FdjDJcjAHtpk4MoGmQiagkXY2pdNV3uH5WShshT5zCCgy5y2AblDgK8uHmyhhoLOPeqhnTP9kmk/7E6k/XKpA3N7nciKskfciisLzZfh4q4Nnd/G3zpAJkpNgWQ7FS9NzQW+rggatunivbcePSsEjpGM5z3HVEm2+drxf0NFd4qvDA/r/hppUiEcIcJTfeWyQN17MHoQL0M=
    # FIREBASE_SECRET
    - secure: E0UxH2tLwezL6T34EIUvH55d/IrC3tXpk7Q4HQreVJT1hctEtQCmTLCiFyXix50eSPRWa1mYWL70I8LXNb2jWliisbAawizDV834/yPxqRq3kYNsYAbmHaaxwB4tMnKfncx4zUOCX1baD5xliKDJ0+Y8DkbBkY7i7f3J2VSjqc/a7tsYsQUpHT8KiZ0Nmsqf8K07OH8urinBSczU7n97+E+EGgtlmV0fhydgiMXsazf+xLs7G7TMJkOftjARuLNMzfFk+rBkmnsXuUp/wLDF8CPoKGh+hCTV+85uhPCSmc+OxJ4jkoLP3y+ZLunrp+pmJoPzaeWmkmzMDrEMM9GN352+PUyp8G/H6qoz8OliVBHWRXIFsvKFxYuYROogGi1Dd6ccl6n24kO8ihKWfPNF2+9rp8hkS8QjEmPDZkXLukz0sU/U4BNkdBKTaocVUiMm87MuCfMk2FzArFZaXYD/Y9WOYKKnIQi8zrtZYaokpn2r9TPh/26DKHyjGWGxqtIg7sxfGV/bprL87QV9wlJcynkkiqZwgwW+zZh4ozAcrwvew75Fy429KzR7GZ9/yKeDxw5fYfFAU9W98tf7gorZ5vD8WThY7DChjAWWOjVFU/50Ekf3GmVRGEaoOtfWSpkWiRI4k32WWHWuUPnA+51cngnHN16dV6yHdBZwOvFFHP0=
